---
homebrew_installed_packages: []

homebrew_cask_apps:
  - iterm2
  - visual-studio-code
  - eloston-chromium
  - firefox
  - docker

macos_dock:
  # Full reset/remove all Applications from Dock
  reset: true
