---
homebrew_installed_packages: []

homebrew_cask_apps:
  # Tools
  - docker
  - tableplus
  - iterm2
  # Development
  - visual-studio-code
  # Browsers
  - firefox
  - eloston-chromium
  - microsoft-edge
  # Collaboration
  - microsoft-teams

# Mac App Store Apps to install
mas_installed_apps:
  - { id: 937984704, name: "Amphetamine" }

macos_dock:
  # Full reset/remove all Applications from Dock
  reset: true
