---
homebrew_installed_packages: []

macos_homebrew:
  install:
    # Path to install homebrew
    prefix: "/usr/local"
    path: "Homebrew"

    # Path to link homebrew's brew command
    bin: /usr/local/bin

    # Path to install homebrew casks
    cask: /Applications

  taps: []

  # Packages to install or uninstall.
  packages: []

  # Casks to install or uninstall.
  # Brewfile paths to process
  brews: []
  
  casks:
    # Tools
    - docker
    - tableplus
    - iterm2
    # Development
    - visual-studio-code
    # Browsers
    - firefox
    - eloston-chromium
    - microsoft-edge
    # Collaboration
    - microsoft-teams

# Mac App Store Apps to install
mas_installed_apps:
  - { id: 937984704, name: "Amphetamine" }

macos_dock:
  # Full reset/remove all Applications from Dock
  reset: true
