---
dockitems_to_persist:
 - name: Microsoft Outlook
   path: /Applications/Microsoft Outlook.app
 - name: Microsoft Teams
   path: /Applications/Microsoft Teams.app
 - name: Firefox
   path: /Applications/Firefox.app
 - name: 1Password
   path: /Applications/1Password 7.app
 - name: iTerm
   path: /Applications/iTerm.app
 - name: Miro
   path: /Applications/Miro.app

macos_computername:
    ComputerName: "mbp-marc"
    HostName: "mbp-marc"
    LocalHostName: "mbp-marc"
    NetBIOSName: "mbp-marc"
