---
dockitems_to_persist:
 - name: Microsoft Outlook
   path: /Applications/Microsoft Outlook.app
 - name: Microsoft Teams
   path: /Applications/Microsoft Teams.app
 - name: Firefox
   path: /Applications/Firefox.app

macos_computername:
    ComputerName: "mbp-marc"
    HostName: "mbp-marc"
    LocalHostName: "mbp-marc"
    NetBIOSName: "mbp-marc"
