---
- hosts: all

  vars_files:
      - default.config.yml
        
  tasks:
    - name: Install homebrew
      include_role:
        name: geerlingguy.homebrew

    - include_tasks: tasks/ms-office.yml
