---
- hosts: all

  vars_files:
      - default.config.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']

    - role: feffi.macos-dock
      tags: ['dock']

  tasks:
    - include_tasks: tasks/set-hostname.yml
