---
- hosts: all

  vars_files:
      - default.config.yml

  collections:
      - community.general
    
  tasks:
      - include_tasks: tasks/ms-office.yml

  roles:
      - community.general.homebrew
      
      - { role: feffi.macos-computername,
          macos_computername: {
            ComputerName: "mbp-safety",
            HostName: "mbp-safety",
            LocalHostName: "mbp-safety",
            NetBIOSName: "mbp-safety"
          }
        }
