---
- hosts: all

  vars_files:
      - default.config.yml

  roles:
     - { role: feffi.macos-computername }

  tasks:
    - name: Install homebrew
      include_role:
        name: geerlingguy.homebrew

    - include_tasks: tasks/ms-office.yml

    - include_tasks: tasks/ms-teams.yml

    - include_tasks: tasks/visual-studio-code.yml

    - include_tasks: tasks/docker.yml

    - include_tasks: tasks/nvm.yml

    - include_tasks: tasks/browsers.yml

    - include_tasks: tasks/iterm2.yml

    - include_tasks: tasks/miro.yml

    - include_tasks: tasks/1password.yml

    - include_tasks: tasks/macos-dock.yml
