---

- name: geerlingguy.homebrew

- name: geerlingguy.mas

- src: https://github.com/feffi/ansible-macos-homebrew.git
  name: feffi.macos-homebrew

- src: https://github.com/feffi/ansible-macos-defaults.git
  name: feffi.macos-defaults

- src: https://github.com/feffi/ansible-macos-ohmyzsh.git
  name: feffi.macos-ohmyzsh
  
- src: https://github.com/feffi/ansible-macos-dock.git
  name: feffi.macos-dock

- name: gantsign.visual-studio-code-extensions
