- name: Install Browsers
  homebrew_cask:
    name:
      - eloston-chromium
      - firefox
      - microsoft-edge
    state: present

- name: Install defaultbrowser
  homebrew:
    name: defaultbrowser

- name: Make Firefox the default browser
  command: defaultbrowser firefox
